spring:
  application:
    name: aeon
  datasource:
    url: jdbc:postgresql://localhost:5432/aeon
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: embedded
  jpa:
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
    show-sql: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  jwt-secret: secret-key
  jwt-expiration-ms: 86400000